version: '3'

services:
  data-store:
    container_name: data_store
    build: server/data-store/
    restart: always
  mosquitto:
    container_name: smart_mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "9810:1883"