name: Data store service

on:
  push:
    branches:
      - master
    paths:
      - 'server/data-store/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Building
        run: |
          docker-compose -f ./docker-compose.yml up -d --build smart_datastore
